# Setup
title:               جایی که جادوگران تا دیروقت بیدارند
tagline:             'منشا اینترنت'
description:         '&#34;	قوانین ممکن است وضع شوند، اما الزاما پیروز نمی‌شوند&#34;	'
url:                 https://soheil-rasouli.github.io/internet-origin/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              سهیل میرزارسولی
  url:               
  email:             soheil.star164+book@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  bidi_enabled: true

collections:
  chapters:
    output: true
    
plugins:
  - jekyll-glossary_tooltip